site_name: Documentation
site_description: 'Education project documentation'
site_author: 'Lanka Software Foundation'
site_url: ''

repo_name: 'moe-lk/documentation'
repo_url: 'https://github.com/moe-lk/documentation'

copyright: 'Copyright &copy; 2018 - 2019 Lanka Software Foundation'

nav:
  - Home : index.md
  - NSIS : nsis.md
  - Information Schema : schema.md
  - Bulk Upload : bulk_upload.md
    
theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  #logo: ''
  language: 'en'
  #favicon: 'images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
